/* T1.6/ADR-04: Memories_GuestFunctionLookup (gptr.h's GCALL macro), the LP64
 * explicit-lookup equivalent of image.c's guest_call_target (ILP32's trap
 * handler does the same binary search, just triggered by a fault instead of
 * a direct call -- see gptr.h's own comment on GCALL for why LP64 cannot
 * reuse that trap). Memories_FunctionMap/Memories_SymbolTable themselves are
 * generated by tools/pc/lp64/gen_fn_table.py into tmp/lp64/gen/fn_table.c
 * (not committed), which every production or test binary using GCALL must
 * link in (or provide its own, smaller stand-ins -- see
 * tests/pc/fn_table_test.c for the latter). */
#include "image.h"
#include "gptr.h"
#include <stdio.h>
#include <stdlib.h>

/* The address closest to (and not past) `address` in Memories_SymbolTable,
 * for the abort message below -- diagnostic only, not on any lookup's
 * success path. Returns Memories_SymbolTableCount if the table is empty. */
static unsigned nearest_symbol_index(unsigned address)
{
    size_t low = 0, high = Memories_SymbolTableCount;
    while (low < high) {
        size_t middle = (low + high) / 2;
        if (Memories_SymbolTable[middle].address < address) {
            low = middle + 1;
        } else {
            high = middle;
        }
    }
    if (low < Memories_SymbolTableCount && Memories_SymbolTable[low].address == address) {
        return (unsigned)low;
    }
    return low > 0 ? (unsigned)(low - 1) : Memories_SymbolTableCount;
}

void (*Memories_GuestFunctionLookup(gaddr address))(void)
{
    size_t low = 0, high = Memories_FunctionMapCount;
    while (low < high) {
        size_t middle = (low + high) / 2;
        if (Memories_FunctionMap[middle].guest < address) {
            low = middle + 1;
        } else {
            high = middle;
        }
    }
    for (; low < Memories_FunctionMapCount && Memories_FunctionMap[low].guest == address; low++) {
        const MemoriesGuestFunction *entry = &Memories_FunctionMap[low];
        /* bank 0 (the common case for all of M1: no overlay loaded yet) is
         * always resident; anything else asks the module registry (M3). */
        if (entry->bank == 0 || Memories_ModuleIsResident(entry->bank, entry->identifier)) {
            return entry->host;
        }
    }
    {
        unsigned nearest = nearest_symbol_index(address);
        if (nearest < Memories_SymbolTableCount) {
            fprintf(stderr, "memories-pc: GCALL at 0x%08x has no native function "
                            "(nearest known symbol: %s at 0x%08x)\n",
                    (unsigned)address, Memories_SymbolTable[nearest].name,
                    Memories_SymbolTable[nearest].address);
        } else {
            fprintf(stderr, "memories-pc: GCALL at 0x%08x has no native function "
                            "(no symbol table linked)\n", (unsigned)address);
        }
    }
    abort();
}
